version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: docker/paidleave.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/nestserver.Dockerfile
    ports:
      - "80:80"
